/*
  # Attachment Style Questionnaire Schema

  ## Overview
  Add tables to store attachment style questionnaire responses and results

  ## New Tables

  ### 1. `attachment_questionnaires`
  Stores completed questionnaires and their analysis
  - `id` (uuid, primary key)
  - `user_id` (uuid, references astra_profiles)
  - `responses` (jsonb) - All 6 question responses
  - `attachment_style` (text) - Diagnosed style (secure, anxious, avoidant, disorganized)
  - `analysis` (text) - Detailed analysis from AI
  - `advice` (text) - Personalized advice
  - `created_at` (timestamptz)

  ## Security
  - RLS enabled
  - Users can only access their own questionnaires

  ## Important Notes
  1. Each user can have multiple questionnaires over time
  2. Responses stored as JSON for flexibility
  3. Analysis and advice generated by AI
*/

-- Create attachment_questionnaires table
CREATE TABLE IF NOT EXISTS attachment_questionnaires (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES astra_profiles(id) ON DELETE CASCADE,
  responses jsonb NOT NULL,
  attachment_style text,
  analysis text,
  advice text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE attachment_questionnaires ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own questionnaires"
  ON attachment_questionnaires FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own questionnaires"
  ON attachment_questionnaires FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own questionnaires"
  ON attachment_questionnaires FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_attachment_questionnaires_user_id ON attachment_questionnaires(user_id);